import { NextIntlClientProvider, useMessages } from "next-intl";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/components/providers";
import { cn } from "@/lib/utils";

const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pifi Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={cn("bg-muted/40", inter.className)}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <TooltipProvider>
            <Providers session={null}>{children}</Providers>
          </TooltipProvider>
          <Toaster />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
